spring: 
  profiles: 
    active: 
      - dev # 等待连接获取的最大超时时间
 
---
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-sinosoft-dev
    
---
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-sinosoft-test
