spring: 
  profiles: 
    active: 
      - dev # 等待连接获取的最大超时时间
      
---
server: 
    port: 7001
    
spring: 
    profiles: dev
    application: 
        name: microservice-config-client
        
eureka:
  instance:
    hostname: eureka7001.com #eureka集群 eureka服务端的实例名称
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机版 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #  设置与Ereka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka
            
---
server: 
    port: 7001
    
spring: 
    profiles: test
    application: 
        name: microservice-config-client
        
eureka:
  instance:
    hostname: eureka7001.com #eureka集群 eureka服务端的实例名称
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机版 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #  设置与Ereka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka
            
            
